default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: fizzbuzz_development

test:
  <<: *default
  database: fizzbuzz_test

production:
  <<: *default
  database: fizzbuzz_production
  username: fizzbuzz
  password: <%= ENV['PROMETHEUS_DATABASE_PASSWORD'] %>
